add_custom_target(hex
  DEPENDS ${OUTPUT_NAME}
  COMMAND ${CMAKE_OBJCOPY} -v -Oihex ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME} ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.hex
)

if(${HAVE_CHECKSUM_TOOL})
  add_custom_target(bin
    DEPENDS ${OUTPUT_NAME}
    COMMAND ${CMAKE_OBJCOPY} -v -Obinary ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME} ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.bin
    COMMAND ${CHECKSUM_TOOL} -p ${DEVICE} -d ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.bin
  )
else()
  add_custom_target(bin
    DEPENDS ${OUTPUT_NAME}
    COMMAND ${CMAKE_OBJCOPY} -v -Obinary ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME} ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.bin
  )
endif()

add_custom_target(lst
  DEPENDS ${OUTPUT_NAME}
  COMMAND ${CMAKE_OBJDUMP} -x -D ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME} > ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.lst
)