add_custom_target(hex
  DEPENDS ${OUTPUT_NAME}
  COMMAND ${CMAKE_OBJCOPY} -Oihex ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}
                ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.hex)

add_custom_target(bin
  DEPENDS ${OUTPUT_NAME}
  COMMAND ${CMAKE_OBJCOPY} -Obinary ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}
                ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.bin)

add_custom_target(lst
  DEPENDS ${OUTPUT_NAME}
  COMMAND ${CMAKE_OBJDUMP} -x -D ${EXECUTABLE_OUTPUT_PATH}/${OUTPUT_NAME}
                       > ${EXECUTABLE_OUTPUT_PATH}/${CMAKE_PROJECT_NAME}.lst)